#!/data/data/com.termux/files/usr/bin/sh
export CLASSPATH="$(pm path com.termux.termuxam 2>&1 </dev/null | cut -d: -f2)"
unset LD_LIBRARY_PATH LD_PRELOAD
exec /system/bin/app_process / com.termux.termuxam.Am "$@"
