#!/data/data/com.termux/files/usr/bin/sh

AM_APK_PATH="@TERMUX_PREFIX@/libexec/termux-am/am.apk"
export CLASSPATH="$AM_APK_PATH"
unset LD_LIBRARY_PATH LD_PRELOAD
exec /system/bin/app_process / com.termux.termuxam.Am "$@"
